---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: "Build & Deploy - PROD"
on:
  push:
    branches:
      - "main"

###############
# Set the Job #
###############
jobs:
  deploy:
    name: Deploy beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true
          # Defaults to the user or organization that owns the workflow file
          scope: "hardisgroupcom"
      - run: yarn
      - run: yarn config set version-git-tag false
      - run: BETAID=$(date '+%Y%m%d%H%M') && yarn version --prepatch --preid="beta$BETAID"
      - run: yarn publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  push_beta_to_registry:
    name: Push Beta Docker image to Docker Hub
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Publish beta to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hardisgroupcom/sfdx-hardis
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: SFDX_HARDIS_VERSION=beta
          tags: "beta"
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/hardisgroupcom/sfdx-hardis:beta"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  push_beta_to_registry_sfdx_stable:
    name: Push Beta Docker image to Docker Hub (with sfdx-cli@stable version)
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Publish beta to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hardisgroupcom/sfdx-hardis
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: SFDX_HARDIS_VERSION=beta,SFDX_CLI_VERSION=stable
          tags: "beta-sfdx-stable"
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/hardisgroupcom/sfdx-hardis:beta-sfdx-stable"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  push_beta_to_registry_sfdx_recommended:
    name: Push Beta Docker image to Docker Hub (with sfdx-cli version recommended by hardis)
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Publish beta to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hardisgroupcom/sfdx-hardis
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: SFDX_HARDIS_VERSION=beta,SFDX_CLI_VERSION=7.111.6
          tags: "beta-sfdx-recommended"
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/hardisgroupcom/sfdx-hardis:beta-sfdx-recommended"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
